### ISSUE TITLE
broken after @percy/cli v1.0.1 upgrade

### ISSUE THREAD

**Issue by okize** [percy/percy-storybook#533]
after upgrading to the latest version of [`@percy/cli`](https://github.com/percy/cli/releases/tag/v1.0.1) I'm running into this error:

```
$ yarn percy storybook ./storybook-static --verbose
yarn run v1.22.10
$ /path/to/node_modules/.bin/percy storybook ./storybook-static --verbose
[percy] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/node_modules/@percy/storybook/dist/hooks/init' imported from /path/to/node_modules/@percy/cli/dist/commands.js
Did you mean to import /path/to/node_modules/@percy/storybook/dist/hooks/init.js?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm unsure if I should report this here or in https://github.com/percy/cli but if I uninstall `@percy/storybook` the cli seems to work correctly:

```
$ yarn percy --help
yarn run v1.22.10
Usage:
  $ percy <command>

Commands:
  exec [options] -- <command>                   Start and stop Percy around a supplied command
  exec:start [options]                          Starts a local Percy snapshot server
  exec:stop [options]                           Stops a local running Percy snapshot server
  exec:ping [options]                           Pings a local running Percy snapshot server
  snapshot [options] <dir|file|sitemap>         Snapshot a static directory, snapshots file, or sitemap URL
  upload [options] <dirname>                    Upload a directory of images to Percy
  build:finalize [options]                      Finalize parallel Percy builds
  build:wait [options]                          Wait for a build to be finished
  config:create [options] [filepath]            Create a Percy config file
  config:validate [options] [filepath]          Validate a Percy config file
  config:migrate [options] [filepath] [output]  Migrate a Percy config file to the latest version
  help [command]                                Display command help

Global options:
  -v, --verbose                                 Log everything
  -q, --quiet                                   Log errors only
  -s, --silent                                  Log nothing
  -h, --help                                    Display command help
  -V, --version                                 Display version

✨  Done in 0.70s.
```

but after installing `@percy/storybook` I get the same error:

```
$ yarn percy --help
yarn run v1.22.10
$ /path/to/node_modules/.bin/percy --help
[percy] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/node_modules/@percy/storybook/dist/hooks/init' imported from /path/to/node_modules/@percy/cli/dist/commands.js
Did you mean to import /path/to/node_modules/@percy/storybook/dist/hooks/init.js?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kschwarz-sz** [comment]
I'm having the same problem for several projects actually. It would be great if somebody could have a look into what's going on :)

**Comment by fernandopasik** [comment]
@percy/cli 1.0.0 doesn't work either, the last version working with storybook is 1.0.0-beta.76

**Comment by unlikelyzero** [comment]
@Robdel12 would your team be able to notify users via email? Basically percy is "down" and blocking build systems which use it worldwide.

**Comment by Robdel12** [comment]
@unlikelyzero Percy isn't down -- the SDKs can be pinned to a specific version that works for your project. There's no requirement to upgrade to the latest version, either. I see you've opened a few issues on the playwright SDK -- that SDK is not related to the expected changes for the storybook SDK. We'll take a look at what you're reporting there to see what's going on.

**Comment by unlikelyzero** [comment]
@Robdel12 i _think_ the issue is that the upstream packages (like percy-playwright and percy-storybook) are not pinned to a tested sdk/core. The percy build system is a bit opaque and would love to help any way I can. https://github.com/percy/percy-playwright/pull/58 is all i could do from my phone

**Comment by benmvp** [comment]
> 👋🏼 This is expected — beta.76 will work until we release an update for this SDK this week. CLI 1.0 had our last breaking change

@Robdel12 - I think this is a bit trickier, unfortunately...

So I've pinned to `@percy/cli@1.0.0-beta.76` which uses exact versions for its dependencies, but `@percy/storybook` uses [caret dependencies](https://github.com/percy/percy-storybook/blob/master/package.json#L36-L38) so even though `@percy/storybook@4.1.0` lists the beta versions, ultimately what gets installed is the latest (non-beta) versions for fresh installs.

So for nested dependencies like `@percy/config` which both `@percy/cli` & `@percy/storybook` use there's now a version mismatch. And what gets hoisted is up for grabs. So with `@percy/cli` pinned but `@percy/storybook` pulling in the latest, I get errors like:

```
percy] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /private/var/folders/hq/kxz2h9bd1t565gh5_zk6768c0000gn/T/tmp-374041hW8FDyub3mw/test-next-ui/node_modules/@percy/config/dist/index.js
require() of ES modules is not supported.
require() of /private/var/folders/hq/kxz2h9bd1t565gh5_zk6768c0000gn/T/tmp-374041hW8FDyub3mw/test-next-ui/node_modules/@percy/config/dist/index.js from /private/var/folders/hq/kxz2h9bd1t565gh5_zk6768c0000gn/T/tmp-374041hW8FDyub3mw/test-next-ui/node_modules/@percy/storybook/dist/hooks/init.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /private/var/folders/hq/kxz2h9bd1t565gh5_zk6768c0000gn/T/tmp-374041hW8FDyub3mw/test-next-ui/node_modules/@percy/config/package.json.
```

i.e. a mix of CJS (beta versions) & ESM (latest versions). Not quite sure how to get a version of `@percy/storybook` that _only_ uses pinned beta versions

**Comment by okize** [comment]
@benmvp could you possibly use [`npm overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) or [`yarn resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to force `@percy/cli` to `1.0.0-beta.76`?

**Comment by bartaz** [comment]
Same here, our renovate PR fails on CI because of this.

**Comment by bartaz** [comment]
> @benmvp could you possibly use [`npm overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) or [`yarn resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to force `@percy/cli` to `1.0.0-beta.76`?

Yes, this seems to work for us, but you need to pin all the Percy packages to beta:

```
  "resolutions": {
    "**/@percy/cli-build": "1.0.0-beta.76",
    "**/@percy/cli-command": "1.0.0-beta.76",
    "**/@percy/cli-config": "1.0.0-beta.76",
    "**/@percy/cli-exec": "1.0.0-beta.76",
    "**/@percy/cli-snapshot": "1.0.0-beta.76",
    "**/@percy/cli-upload": "1.0.0-beta.76",
    "**/@percy/cli": "1.0.0-beta.76",
    "**/@percy/client": "1.0.0-beta.76",
    "**/@percy/config": "1.0.0-beta.76",
    "**/@percy/core": "1.0.0-beta.76",
    "**/@percy/dom": "1.0.0-beta.76",
    "**/@percy/env": "1.0.0-beta.76",
    "**/@percy/logger": "1.0.0-beta.76"
  },
  ```

**Comment by benmvp** [comment]
> Yes, this seems to work for us, but you need to pin all the Percy packages to beta:

Yep, it does! Here's what we did for npm overrides:

```json
{
  "overrides": {
    "@percy/cli-build": "1.0.0-beta.76",
    "@percy/cli-command": "1.0.0-beta.76",
    "@percy/cli-config": "1.0.0-beta.76",
    "@percy/cli-exec": "1.0.0-beta.76",
    "@percy/cli-snapshot": "1.0.0-beta.76",
    "@percy/cli-upload": "1.0.0-beta.76",
    "@percy/cli": "1.0.0-beta.76",
    "@percy/client": "1.0.0-beta.76",
    "@percy/config": "1.0.0-beta.76",
    "@percy/core": "1.0.0-beta.76",
    "@percy/dom": "1.0.0-beta.76",
    "@percy/env": "1.0.0-beta.76",
    "@percy/logger": "1.0.0-beta.76"
  }
}
```

Thanks @okize and @bartaz!

**Comment by unlikelyzero** [comment]
I think the root of the issue is mostly that these packages aren't following the standard semver format for npm/yarn. A major change was introduced that was not backcompat on a patch release _which broke the entire package system with no way to recover_ .

With the latest fixes in place, this package should look like:

`@percy/storybook`: 2.1.1`
 - `@percy/cli` should be on `~2.1.1`

2.x.y because a major node version was removed
x.1.y to signify that major changes were observed, 
x.y.1 to fix **on top of the fix**

the `~` is used so that users of `@percy/storybook` won't be affected by deprecated node versions on the patch (z) release.

**Comment by Robdel12** [comment]
> I think the root of the issue is mostly that these packages aren't following the standard semver format for npm/yarn.

This is not true. Breaking changes can be made for anything with a pre-release tag or non-major (1.0.0-beta.1 or 0.x.x). We made our final breaking changes prior to 1.x release. One of those breaking changes was to drop Node 12, which is EOL this month. All other SDKs needed a bug bump to update them to Node 14, which aligns them with the breaking change the CLI has. Again, you're not forced to upgrade immediately. 

The storybook SDK on the other hand needs an update which will fix the config schema change we made upstream https://github.com/percy/cli/pull/804. That + aligning this SDK with Node 14 will be coming this week.

**Comment by benmvp** [comment]
Thanks, @Robdel12. Looking forward to it. Appreciate your work on this

**Comment by Robdel12** [comment]
Alrighty y'all, upgrading to 4.2.0 will fix these issues 🎉 https://github.com/percy/percy-storybook/releases/tag/v4.2.0

**Comment by okize** [comment]
@Robdel12 I can confirm this fixed the issue for me, thank you for the quick turnaround! 🙏

**Comment by tmcconechy** [comment]
Hi All,

The issue about missing imports is fixed by now i get this instead? I looked in the link but it doesnt really give any clue as to what one might do to fix it?

```
    You need to run with a version of node that supports ES Modules in the VM API. See https://jestjs.io/docs/ecmascript-modules

      22 |       document.querySelector('ids-theme-switcher')?.setAttribute('mode', 'contrast');
      23 |     });
    > 24 |     await percySnapshot(page, 'ids-accordion-new-contrast');
         |                        ^
      25 |   });
      26 | });
      27 |
```

**Comment by tmcconechy** [comment]
Posted one here with details. Thanks @Robdel12 https://github.com/percy/cli/issues/869

**Comment by benmvp** [comment]
> @Robdel12 I can confirm this fixed the issue for me, thank you for the quick turnaround! 🙏

Same here! Thanks again!
